set(_CATKIN_CURRENT_PACKAGE "statek_calibrate")
set(statek_calibrate_VERSION "0.0.0")
set(statek_calibrate_MAINTAINER "statek <statek@todo.todo>")
set(statek_calibrate_PACKAGE_FORMAT "2")
set(statek_calibrate_BUILD_DEPENDS "camera_calibration" "statek_hw")
set(statek_calibrate_BUILD_EXPORT_DEPENDS "camera_calibration" "statek_hw")
set(statek_calibrate_BUILDTOOL_DEPENDS "catkin")
set(statek_calibrate_BUILDTOOL_EXPORT_DEPENDS )
set(statek_calibrate_EXEC_DEPENDS "camera_calibration" "statek_hw")
set(statek_calibrate_RUN_DEPENDS "camera_calibration" "statek_hw")
set(statek_calibrate_TEST_DEPENDS )
set(statek_calibrate_DOC_DEPENDS )
set(statek_calibrate_URL_WEBSITE "")
set(statek_calibrate_URL_BUGTRACKER "")
set(statek_calibrate_URL_REPOSITORY "")
set(statek_calibrate_DEPRECATED "")