# wheel config
wheel_radius: 0.12 # In [m].
wheel_max_angular_velocity: 1.9 # How fast wheels can rotate in [rad/s].

# kinematic config
distance_between_wheels: 0.62 # In [m].
max_linear_velocity: 0.0 # How fast UAV can move forward in m/s defined as wheel_radius*wheel_max_angular_velocity.
max_angular_velocity: 0.0 # How fast UAV can rotate around it's center in [rad/s] defined as max_linear_velocity / (distance_between_wheels / 2).

# closed loop control
loop_update_rate_ms : 30
smoothing_factor: 0.19
left_motor_pid: [1, 5.44140023, 0.0] # Kp, ki, kd.
right_motor_pid: [1, 5.44140023, 0.0]

# imu config
imu_update_rate_ms: 30
acc_bias: [24859.7910156, 19768.7460938, -6333.76464844]
gyro_bias: [-407.208129883, -211.160003662, -68.2262496948]
mag_bias: [1012.87866211, 577.100952148, 105.396537781]
mag_scale: [0.979166686535, 1.11904764175, 0.921568632126]
mag_dec: [6, 10, 0]

# odom config
odom_update_rate_ms: 30
