goal_area: 1 # Radius around goal point that will count as a goal.
solver_options: "Integer print_level 0\nSparse true forward\nSparse true reverse\nNumeric max_cpu_time 0.7\n"

# Horizon parameters.
# _forward will be used when orientation error is 0.
# _rotate will be used when absolute orientation error equals to pi.
# values in between will be interpolated.
horizon_duration_forward: 15
horizon_sampling_forward: 0.5
horizon_duration_rotate: 3
horizon_sampling_rotate: 0.1

pose_weight: 10
cte_weight: 30
oe_weight: 700000

linear_velocity_weight: 0
angular_velocity_weight: 0

linear_velocity_delta_weight: 3
angular_velocity_delta_weight: 0.1