float32[3] acc_bias # Some value from calibrated MPU9250.
float32[3] gyro_bias # Some value from calibrated MPU9250.
float32[3] mag_bias # Some value from calibrated MPU9250.
float32[3] mag_scale # Some value from calibrated MPU9250.
float32 mag_dec # In degrees.
---
bool success # Set to true on success.