// Generated by gencpp from file statek_hw/Encoder.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_ENCODER_H
#define STATEK_HW_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace statek_hw
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , acceleration(0.0)
    , velocity(0.0)
    , position(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration(0.0)
    , velocity(0.0)
    , position(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _acceleration_type;
  _acceleration_type acceleration;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::statek_hw::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::statek_hw::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::statek_hw::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::statek_hw::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::Encoder_<ContainerAllocator1> & lhs, const ::statek_hw::Encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration == rhs.acceleration &&
    lhs.velocity == rhs.velocity &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::Encoder_<ContainerAllocator1> & lhs, const ::statek_hw::Encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72b8bd04d914e248fb0847af003c28c1";
  }

  static const char* value(const ::statek_hw::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72b8bd04d914e248ULL;
  static const uint64_t static_value2 = 0xfb0847af003c28c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/Encoder";
  }

  static const char* value(const ::statek_hw::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 acceleration # In rad/s^2.\n"
"float64 velocity # In rad/s.\n"
"float64 position # In rad.\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::statek_hw::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.velocity);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_ENCODER_H
