// Generated by gencpp from file statek_hw/RunModelIdentification.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNMODELIDENTIFICATION_H
#define STATEK_HW_MESSAGE_RUNMODELIDENTIFICATION_H

#include <ros/service_traits.h>


#include <statek_hw/RunModelIdentificationRequest.h>
#include <statek_hw/RunModelIdentificationResponse.h>


namespace statek_hw
{

struct RunModelIdentification
{

typedef RunModelIdentificationRequest Request;
typedef RunModelIdentificationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunModelIdentification
} // namespace statek_hw


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::statek_hw::RunModelIdentification > {
  static const char* value()
  {
    return "d0062710edaa1716482716b90a44c970";
  }

  static const char* value(const ::statek_hw::RunModelIdentification&) { return value(); }
};

template<>
struct DataType< ::statek_hw::RunModelIdentification > {
  static const char* value()
  {
    return "statek_hw/RunModelIdentification";
  }

  static const char* value(const ::statek_hw::RunModelIdentification&) { return value(); }
};


// service_traits::MD5Sum< ::statek_hw::RunModelIdentificationRequest> should match
// service_traits::MD5Sum< ::statek_hw::RunModelIdentification >
template<>
struct MD5Sum< ::statek_hw::RunModelIdentificationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::RunModelIdentification >::value();
  }
  static const char* value(const ::statek_hw::RunModelIdentificationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::RunModelIdentificationRequest> should match
// service_traits::DataType< ::statek_hw::RunModelIdentification >
template<>
struct DataType< ::statek_hw::RunModelIdentificationRequest>
{
  static const char* value()
  {
    return DataType< ::statek_hw::RunModelIdentification >::value();
  }
  static const char* value(const ::statek_hw::RunModelIdentificationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::statek_hw::RunModelIdentificationResponse> should match
// service_traits::MD5Sum< ::statek_hw::RunModelIdentification >
template<>
struct MD5Sum< ::statek_hw::RunModelIdentificationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::RunModelIdentification >::value();
  }
  static const char* value(const ::statek_hw::RunModelIdentificationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::RunModelIdentificationResponse> should match
// service_traits::DataType< ::statek_hw::RunModelIdentification >
template<>
struct DataType< ::statek_hw::RunModelIdentificationResponse>
{
  static const char* value()
  {
    return DataType< ::statek_hw::RunModelIdentification >::value();
  }
  static const char* value(const ::statek_hw::RunModelIdentificationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNMODELIDENTIFICATION_H
