// Generated by gencpp from file statek_hw/RunModelIdentificationRequest.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNMODELIDENTIFICATIONREQUEST_H
#define STATEK_HW_MESSAGE_RUNMODELIDENTIFICATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace statek_hw
{
template <class ContainerAllocator>
struct RunModelIdentificationRequest_
{
  typedef RunModelIdentificationRequest_<ContainerAllocator> Type;

  RunModelIdentificationRequest_()
    : identification_time_ms(0)  {
    }
  RunModelIdentificationRequest_(const ContainerAllocator& _alloc)
    : identification_time_ms(0)  {
  (void)_alloc;
    }



   typedef uint32_t _identification_time_ms_type;
  _identification_time_ms_type identification_time_ms;





  typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RunModelIdentificationRequest_

typedef ::statek_hw::RunModelIdentificationRequest_<std::allocator<void> > RunModelIdentificationRequest;

typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationRequest > RunModelIdentificationRequestPtr;
typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationRequest const> RunModelIdentificationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator1> & lhs, const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.identification_time_ms == rhs.identification_time_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator1> & lhs, const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a1d96b6498339e94d9e98e6c92d5137";
  }

  static const char* value(const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a1d96b6498339e9ULL;
  static const uint64_t static_value2 = 0x4d9e98e6c92d5137ULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/RunModelIdentificationRequest";
  }

  static const char* value(const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 identification_time_ms\n"
;
  }

  static const char* value(const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.identification_time_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunModelIdentificationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::RunModelIdentificationRequest_<ContainerAllocator>& v)
  {
    s << indent << "identification_time_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.identification_time_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNMODELIDENTIFICATIONREQUEST_H
