// Generated by gencpp from file statek_hw/RunVelocityTestRequest.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNVELOCITYTESTREQUEST_H
#define STATEK_HW_MESSAGE_RUNVELOCITYTESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace statek_hw
{
template <class ContainerAllocator>
struct RunVelocityTestRequest_
{
  typedef RunVelocityTestRequest_<ContainerAllocator> Type;

  RunVelocityTestRequest_()
    : time_ms(0)  {
    }
  RunVelocityTestRequest_(const ContainerAllocator& _alloc)
    : time_ms(0)  {
  (void)_alloc;
    }



   typedef uint32_t _time_ms_type;
  _time_ms_type time_ms;





  typedef boost::shared_ptr< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RunVelocityTestRequest_

typedef ::statek_hw::RunVelocityTestRequest_<std::allocator<void> > RunVelocityTestRequest;

typedef boost::shared_ptr< ::statek_hw::RunVelocityTestRequest > RunVelocityTestRequestPtr;
typedef boost::shared_ptr< ::statek_hw::RunVelocityTestRequest const> RunVelocityTestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator1> & lhs, const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.time_ms == rhs.time_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator1> & lhs, const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6301565e50e0b100332dde1661ab3ebc";
  }

  static const char* value(const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6301565e50e0b100ULL;
  static const uint64_t static_value2 = 0x332dde1661ab3ebcULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/RunVelocityTestRequest";
  }

  static const char* value(const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 time_ms # Test time in milliseconds.\n"
;
  }

  static const char* value(const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunVelocityTestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::RunVelocityTestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::RunVelocityTestRequest_<ContainerAllocator>& v)
  {
    s << indent << "time_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNVELOCITYTESTREQUEST_H
