// Generated by gencpp from file statek_hw/RunVelocityTestResponse.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNVELOCITYTESTRESPONSE_H
#define STATEK_HW_MESSAGE_RUNVELOCITYTESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace statek_hw
{
template <class ContainerAllocator>
struct RunVelocityTestResponse_
{
  typedef RunVelocityTestResponse_<ContainerAllocator> Type;

  RunVelocityTestResponse_()
    : success(false)
    , velocity(0.0)  {
    }
  RunVelocityTestResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RunVelocityTestResponse_

typedef ::statek_hw::RunVelocityTestResponse_<std::allocator<void> > RunVelocityTestResponse;

typedef boost::shared_ptr< ::statek_hw::RunVelocityTestResponse > RunVelocityTestResponsePtr;
typedef boost::shared_ptr< ::statek_hw::RunVelocityTestResponse const> RunVelocityTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator1> & lhs, const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator1> & lhs, const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "738dd6bd6e6687eab1176abf1ea50abc";
  }

  static const char* value(const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x738dd6bd6e6687eaULL;
  static const uint64_t static_value2 = 0xb1176abf1ea50abcULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/RunVelocityTestResponse";
  }

  static const char* value(const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success # Set to true on success\n"
"float64 velocity # Found velocity in rad/s.\n"
;
  }

  static const char* value(const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunVelocityTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::RunVelocityTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::RunVelocityTestResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNVELOCITYTESTRESPONSE_H
