// Generated by gencpp from file statek_hw/SetImuParams.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_SETIMUPARAMS_H
#define STATEK_HW_MESSAGE_SETIMUPARAMS_H

#include <ros/service_traits.h>


#include <statek_hw/SetImuParamsRequest.h>
#include <statek_hw/SetImuParamsResponse.h>


namespace statek_hw
{

struct SetImuParams
{

typedef SetImuParamsRequest Request;
typedef SetImuParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetImuParams
} // namespace statek_hw


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::statek_hw::SetImuParams > {
  static const char* value()
  {
    return "fc6fb75dba4829e04baa420f42b24adc";
  }

  static const char* value(const ::statek_hw::SetImuParams&) { return value(); }
};

template<>
struct DataType< ::statek_hw::SetImuParams > {
  static const char* value()
  {
    return "statek_hw/SetImuParams";
  }

  static const char* value(const ::statek_hw::SetImuParams&) { return value(); }
};


// service_traits::MD5Sum< ::statek_hw::SetImuParamsRequest> should match
// service_traits::MD5Sum< ::statek_hw::SetImuParams >
template<>
struct MD5Sum< ::statek_hw::SetImuParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::SetImuParams >::value();
  }
  static const char* value(const ::statek_hw::SetImuParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::SetImuParamsRequest> should match
// service_traits::DataType< ::statek_hw::SetImuParams >
template<>
struct DataType< ::statek_hw::SetImuParamsRequest>
{
  static const char* value()
  {
    return DataType< ::statek_hw::SetImuParams >::value();
  }
  static const char* value(const ::statek_hw::SetImuParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::statek_hw::SetImuParamsResponse> should match
// service_traits::MD5Sum< ::statek_hw::SetImuParams >
template<>
struct MD5Sum< ::statek_hw::SetImuParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::SetImuParams >::value();
  }
  static const char* value(const ::statek_hw::SetImuParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::SetImuParamsResponse> should match
// service_traits::DataType< ::statek_hw::SetImuParams >
template<>
struct DataType< ::statek_hw::SetImuParamsResponse>
{
  static const char* value()
  {
    return DataType< ::statek_hw::SetImuParams >::value();
  }
  static const char* value(const ::statek_hw::SetImuParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATEK_HW_MESSAGE_SETIMUPARAMS_H
