set(_CATKIN_CURRENT_PACKAGE "statek_config")
set(statek_config_VERSION "0.0.0")
set(statek_config_MAINTAINER "statek <statek@todo.todo>")
set(statek_config_PACKAGE_FORMAT "2")
set(statek_config_BUILD_DEPENDS )
set(statek_config_BUILD_EXPORT_DEPENDS )
set(statek_config_BUILDTOOL_DEPENDS "catkin")
set(statek_config_BUILDTOOL_EXPORT_DEPENDS )
set(statek_config_EXEC_DEPENDS )
set(statek_config_RUN_DEPENDS )
set(statek_config_TEST_DEPENDS )
set(statek_config_DOC_DEPENDS )
set(statek_config_URL_WEBSITE "")
set(statek_config_URL_BUGTRACKER "")
set(statek_config_URL_REPOSITORY "")
set(statek_config_DEPRECATED "")