set(_CATKIN_CURRENT_PACKAGE "statek_hw")
set(statek_hw_VERSION "0.0.0")
set(statek_hw_MAINTAINER "statek <statek@todo.todo>")
set(statek_hw_PACKAGE_FORMAT "2")
set(statek_hw_BUILD_DEPENDS "rospy" "roscpp" "std_msgs" "rospkg" "image_transport" "cv_bridge" "message_generation")
set(statek_hw_BUILD_EXPORT_DEPENDS "rospy" "roscpp" "std_msgs" "rospkg" "image_transport" "cv_bridge")
set(statek_hw_BUILDTOOL_DEPENDS "catkin")
set(statek_hw_BUILDTOOL_EXPORT_DEPENDS )
set(statek_hw_EXEC_DEPENDS "rospy" "roscpp" "std_msgs" "rospkg" "image_transport" "cv_bridge" "stereo_image_proc" "message_runtime")
set(statek_hw_RUN_DEPENDS "rospy" "roscpp" "std_msgs" "rospkg" "image_transport" "cv_bridge" "stereo_image_proc" "message_runtime")
set(statek_hw_TEST_DEPENDS )
set(statek_hw_DOC_DEPENDS )
set(statek_hw_URL_WEBSITE "")
set(statek_hw_URL_BUGTRACKER "")
set(statek_hw_URL_REPOSITORY "")
set(statek_hw_DEPRECATED "")