// Generated by gencpp from file statek_hw/RunImuCalibration.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNIMUCALIBRATION_H
#define STATEK_HW_MESSAGE_RUNIMUCALIBRATION_H

#include <ros/service_traits.h>


#include <statek_hw/RunImuCalibrationRequest.h>
#include <statek_hw/RunImuCalibrationResponse.h>


namespace statek_hw
{

struct RunImuCalibration
{

typedef RunImuCalibrationRequest Request;
typedef RunImuCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunImuCalibration
} // namespace statek_hw


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::statek_hw::RunImuCalibration > {
  static const char* value()
  {
    return "6cd60c1db4de1bdcd039c0b56b7d1d09";
  }

  static const char* value(const ::statek_hw::RunImuCalibration&) { return value(); }
};

template<>
struct DataType< ::statek_hw::RunImuCalibration > {
  static const char* value()
  {
    return "statek_hw/RunImuCalibration";
  }

  static const char* value(const ::statek_hw::RunImuCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::statek_hw::RunImuCalibrationRequest> should match
// service_traits::MD5Sum< ::statek_hw::RunImuCalibration >
template<>
struct MD5Sum< ::statek_hw::RunImuCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::RunImuCalibration >::value();
  }
  static const char* value(const ::statek_hw::RunImuCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::RunImuCalibrationRequest> should match
// service_traits::DataType< ::statek_hw::RunImuCalibration >
template<>
struct DataType< ::statek_hw::RunImuCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::statek_hw::RunImuCalibration >::value();
  }
  static const char* value(const ::statek_hw::RunImuCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::statek_hw::RunImuCalibrationResponse> should match
// service_traits::MD5Sum< ::statek_hw::RunImuCalibration >
template<>
struct MD5Sum< ::statek_hw::RunImuCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::RunImuCalibration >::value();
  }
  static const char* value(const ::statek_hw::RunImuCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::RunImuCalibrationResponse> should match
// service_traits::DataType< ::statek_hw::RunImuCalibration >
template<>
struct DataType< ::statek_hw::RunImuCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::statek_hw::RunImuCalibration >::value();
  }
  static const char* value(const ::statek_hw::RunImuCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNIMUCALIBRATION_H
