// Generated by gencpp from file statek_hw/RunModelIdentificationResponse.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNMODELIDENTIFICATIONRESPONSE_H
#define STATEK_HW_MESSAGE_RUNMODELIDENTIFICATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace statek_hw
{
template <class ContainerAllocator>
struct RunModelIdentificationResponse_
{
  typedef RunModelIdentificationResponse_<ContainerAllocator> Type;

  RunModelIdentificationResponse_()
    : success(false)
    , sampling_time(0.0)
    , samples()  {
      samples.assign(0.0);
  }
  RunModelIdentificationResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , sampling_time(0.0)
    , samples()  {
  (void)_alloc;
      samples.assign(0.0);
  }



   typedef uint8_t _success_type;
  _success_type success;

   typedef double _sampling_time_type;
  _sampling_time_type sampling_time;

   typedef boost::array<double, 100>  _samples_type;
  _samples_type samples;





  typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RunModelIdentificationResponse_

typedef ::statek_hw::RunModelIdentificationResponse_<std::allocator<void> > RunModelIdentificationResponse;

typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationResponse > RunModelIdentificationResponsePtr;
typedef boost::shared_ptr< ::statek_hw::RunModelIdentificationResponse const> RunModelIdentificationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator1> & lhs, const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.sampling_time == rhs.sampling_time &&
    lhs.samples == rhs.samples;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator1> & lhs, const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e73ac1d7ab01f6a97c7866cdfb45f3b";
  }

  static const char* value(const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e73ac1d7ab01f6aULL;
  static const uint64_t static_value2 = 0x97c7866cdfb45f3bULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/RunModelIdentificationResponse";
  }

  static const char* value(const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float64 sampling_time\n"
"float64[100] samples\n"
;
  }

  static const char* value(const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.sampling_time);
      stream.next(m.samples);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunModelIdentificationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::RunModelIdentificationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "sampling_time: ";
    Printer<double>::stream(s, indent + "  ", v.sampling_time);
    s << indent << "samples[]" << std::endl;
    for (size_t i = 0; i < v.samples.size(); ++i)
    {
      s << indent << "  samples[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.samples[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNMODELIDENTIFICATIONRESPONSE_H
