// Generated by gencpp from file statek_hw/RunVelocityTest.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_RUNVELOCITYTEST_H
#define STATEK_HW_MESSAGE_RUNVELOCITYTEST_H

#include <ros/service_traits.h>


#include <statek_hw/RunVelocityTestRequest.h>
#include <statek_hw/RunVelocityTestResponse.h>


namespace statek_hw
{

struct RunVelocityTest
{

typedef RunVelocityTestRequest Request;
typedef RunVelocityTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunVelocityTest
} // namespace statek_hw


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::statek_hw::RunVelocityTest > {
  static const char* value()
  {
    return "0da28cc5facb55eb49569bd980fe316c";
  }

  static const char* value(const ::statek_hw::RunVelocityTest&) { return value(); }
};

template<>
struct DataType< ::statek_hw::RunVelocityTest > {
  static const char* value()
  {
    return "statek_hw/RunVelocityTest";
  }

  static const char* value(const ::statek_hw::RunVelocityTest&) { return value(); }
};


// service_traits::MD5Sum< ::statek_hw::RunVelocityTestRequest> should match
// service_traits::MD5Sum< ::statek_hw::RunVelocityTest >
template<>
struct MD5Sum< ::statek_hw::RunVelocityTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::RunVelocityTest >::value();
  }
  static const char* value(const ::statek_hw::RunVelocityTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::RunVelocityTestRequest> should match
// service_traits::DataType< ::statek_hw::RunVelocityTest >
template<>
struct DataType< ::statek_hw::RunVelocityTestRequest>
{
  static const char* value()
  {
    return DataType< ::statek_hw::RunVelocityTest >::value();
  }
  static const char* value(const ::statek_hw::RunVelocityTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::statek_hw::RunVelocityTestResponse> should match
// service_traits::MD5Sum< ::statek_hw::RunVelocityTest >
template<>
struct MD5Sum< ::statek_hw::RunVelocityTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::RunVelocityTest >::value();
  }
  static const char* value(const ::statek_hw::RunVelocityTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::RunVelocityTestResponse> should match
// service_traits::DataType< ::statek_hw::RunVelocityTest >
template<>
struct DataType< ::statek_hw::RunVelocityTestResponse>
{
  static const char* value()
  {
    return DataType< ::statek_hw::RunVelocityTest >::value();
  }
  static const char* value(const ::statek_hw::RunVelocityTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATEK_HW_MESSAGE_RUNVELOCITYTEST_H
