// Generated by gencpp from file statek_hw/SetImuParamsRequest.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_SETIMUPARAMSREQUEST_H
#define STATEK_HW_MESSAGE_SETIMUPARAMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace statek_hw
{
template <class ContainerAllocator>
struct SetImuParamsRequest_
{
  typedef SetImuParamsRequest_<ContainerAllocator> Type;

  SetImuParamsRequest_()
    : imu_update_rate_ms(0)
    , acc_bias()
    , gyro_bias()
    , mag_bias()
    , mag_scale()
    , mag_dec()  {
      acc_bias.assign(0.0);

      gyro_bias.assign(0.0);

      mag_bias.assign(0.0);

      mag_scale.assign(0.0);

      mag_dec.assign(0);
  }
  SetImuParamsRequest_(const ContainerAllocator& _alloc)
    : imu_update_rate_ms(0)
    , acc_bias()
    , gyro_bias()
    , mag_bias()
    , mag_scale()
    , mag_dec()  {
  (void)_alloc;
      acc_bias.assign(0.0);

      gyro_bias.assign(0.0);

      mag_bias.assign(0.0);

      mag_scale.assign(0.0);

      mag_dec.assign(0);
  }



   typedef uint32_t _imu_update_rate_ms_type;
  _imu_update_rate_ms_type imu_update_rate_ms;

   typedef boost::array<double, 3>  _acc_bias_type;
  _acc_bias_type acc_bias;

   typedef boost::array<double, 3>  _gyro_bias_type;
  _gyro_bias_type gyro_bias;

   typedef boost::array<double, 3>  _mag_bias_type;
  _mag_bias_type mag_bias;

   typedef boost::array<double, 3>  _mag_scale_type;
  _mag_scale_type mag_scale;

   typedef boost::array<int16_t, 3>  _mag_dec_type;
  _mag_dec_type mag_dec;





  typedef boost::shared_ptr< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetImuParamsRequest_

typedef ::statek_hw::SetImuParamsRequest_<std::allocator<void> > SetImuParamsRequest;

typedef boost::shared_ptr< ::statek_hw::SetImuParamsRequest > SetImuParamsRequestPtr;
typedef boost::shared_ptr< ::statek_hw::SetImuParamsRequest const> SetImuParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::SetImuParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::SetImuParamsRequest_<ContainerAllocator1> & lhs, const ::statek_hw::SetImuParamsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.imu_update_rate_ms == rhs.imu_update_rate_ms &&
    lhs.acc_bias == rhs.acc_bias &&
    lhs.gyro_bias == rhs.gyro_bias &&
    lhs.mag_bias == rhs.mag_bias &&
    lhs.mag_scale == rhs.mag_scale &&
    lhs.mag_dec == rhs.mag_dec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::SetImuParamsRequest_<ContainerAllocator1> & lhs, const ::statek_hw::SetImuParamsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b52e44d9a6cc076ecccb46df6d4a341";
  }

  static const char* value(const ::statek_hw::SetImuParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b52e44d9a6cc076ULL;
  static const uint64_t static_value2 = 0xecccb46df6d4a341ULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/SetImuParamsRequest";
  }

  static const char* value(const ::statek_hw::SetImuParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 imu_update_rate_ms\n"
"float64[3] acc_bias # Some value from calibrated MPU9250.\n"
"float64[3] gyro_bias # Some value from calibrated MPU9250.\n"
"float64[3] mag_bias # Some value from calibrated MPU9250.\n"
"float64[3] mag_scale # Some value from calibrated MPU9250.\n"
"int16[3] mag_dec # Deg, min, sec.\n"
;
  }

  static const char* value(const ::statek_hw::SetImuParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imu_update_rate_ms);
      stream.next(m.acc_bias);
      stream.next(m.gyro_bias);
      stream.next(m.mag_bias);
      stream.next(m.mag_scale);
      stream.next(m.mag_dec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetImuParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::SetImuParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::SetImuParamsRequest_<ContainerAllocator>& v)
  {
    s << indent << "imu_update_rate_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.imu_update_rate_ms);
    s << indent << "acc_bias[]" << std::endl;
    for (size_t i = 0; i < v.acc_bias.size(); ++i)
    {
      s << indent << "  acc_bias[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acc_bias[i]);
    }
    s << indent << "gyro_bias[]" << std::endl;
    for (size_t i = 0; i < v.gyro_bias.size(); ++i)
    {
      s << indent << "  gyro_bias[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gyro_bias[i]);
    }
    s << indent << "mag_bias[]" << std::endl;
    for (size_t i = 0; i < v.mag_bias.size(); ++i)
    {
      s << indent << "  mag_bias[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.mag_bias[i]);
    }
    s << indent << "mag_scale[]" << std::endl;
    for (size_t i = 0; i < v.mag_scale.size(); ++i)
    {
      s << indent << "  mag_scale[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.mag_scale[i]);
    }
    s << indent << "mag_dec[]" << std::endl;
    for (size_t i = 0; i < v.mag_dec.size(); ++i)
    {
      s << indent << "  mag_dec[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.mag_dec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_SETIMUPARAMSREQUEST_H
