// Generated by gencpp from file statek_hw/SetImuParamsResponse.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_SETIMUPARAMSRESPONSE_H
#define STATEK_HW_MESSAGE_SETIMUPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace statek_hw
{
template <class ContainerAllocator>
struct SetImuParamsResponse_
{
  typedef SetImuParamsResponse_<ContainerAllocator> Type;

  SetImuParamsResponse_()
    : success(false)  {
    }
  SetImuParamsResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetImuParamsResponse_

typedef ::statek_hw::SetImuParamsResponse_<std::allocator<void> > SetImuParamsResponse;

typedef boost::shared_ptr< ::statek_hw::SetImuParamsResponse > SetImuParamsResponsePtr;
typedef boost::shared_ptr< ::statek_hw::SetImuParamsResponse const> SetImuParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::statek_hw::SetImuParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::statek_hw::SetImuParamsResponse_<ContainerAllocator1> & lhs, const ::statek_hw::SetImuParamsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::statek_hw::SetImuParamsResponse_<ContainerAllocator1> & lhs, const ::statek_hw::SetImuParamsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace statek_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::statek_hw::SetImuParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "statek_hw/SetImuParamsResponse";
  }

  static const char* value(const ::statek_hw::SetImuParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success # Set to true on success.\n"
;
  }

  static const char* value(const ::statek_hw::SetImuParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetImuParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::statek_hw::SetImuParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::statek_hw::SetImuParamsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATEK_HW_MESSAGE_SETIMUPARAMSRESPONSE_H
