// Generated by gencpp from file statek_hw/SetOdomParams.msg
// DO NOT EDIT!


#ifndef STATEK_HW_MESSAGE_SETODOMPARAMS_H
#define STATEK_HW_MESSAGE_SETODOMPARAMS_H

#include <ros/service_traits.h>


#include <statek_hw/SetOdomParamsRequest.h>
#include <statek_hw/SetOdomParamsResponse.h>


namespace statek_hw
{

struct SetOdomParams
{

typedef SetOdomParamsRequest Request;
typedef SetOdomParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOdomParams
} // namespace statek_hw


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::statek_hw::SetOdomParams > {
  static const char* value()
  {
    return "1c8fcad49bde18e0cd305a59dcc09b29";
  }

  static const char* value(const ::statek_hw::SetOdomParams&) { return value(); }
};

template<>
struct DataType< ::statek_hw::SetOdomParams > {
  static const char* value()
  {
    return "statek_hw/SetOdomParams";
  }

  static const char* value(const ::statek_hw::SetOdomParams&) { return value(); }
};


// service_traits::MD5Sum< ::statek_hw::SetOdomParamsRequest> should match
// service_traits::MD5Sum< ::statek_hw::SetOdomParams >
template<>
struct MD5Sum< ::statek_hw::SetOdomParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::SetOdomParams >::value();
  }
  static const char* value(const ::statek_hw::SetOdomParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::SetOdomParamsRequest> should match
// service_traits::DataType< ::statek_hw::SetOdomParams >
template<>
struct DataType< ::statek_hw::SetOdomParamsRequest>
{
  static const char* value()
  {
    return DataType< ::statek_hw::SetOdomParams >::value();
  }
  static const char* value(const ::statek_hw::SetOdomParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::statek_hw::SetOdomParamsResponse> should match
// service_traits::MD5Sum< ::statek_hw::SetOdomParams >
template<>
struct MD5Sum< ::statek_hw::SetOdomParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::statek_hw::SetOdomParams >::value();
  }
  static const char* value(const ::statek_hw::SetOdomParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::statek_hw::SetOdomParamsResponse> should match
// service_traits::DataType< ::statek_hw::SetOdomParams >
template<>
struct DataType< ::statek_hw::SetOdomParamsResponse>
{
  static const char* value()
  {
    return DataType< ::statek_hw::SetOdomParams >::value();
  }
  static const char* value(const ::statek_hw::SetOdomParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATEK_HW_MESSAGE_SETODOMPARAMS_H
