uint32 imu_update_rate_ms
float64[3] acc_bias # Some value from calibrated MPU9250.
float64[3] gyro_bias # Some value from calibrated MPU9250.
float64[3] mag_bias # Some value from calibrated MPU9250.
float64[3] mag_scale # Some value from calibrated MPU9250.
float64 mag_dec_deg # From internet or whatever.
float64 mag_dec_min
float64 mag_dec_sec
---
bool success # Set to true on success.